// ==========================================
// state.js - إدارة حالة التطبيق والترجمة
// ==========================================

export const state = {
    currentLang: localStorage.getItem('appLanguage') || 'ar',
    allDoctors: [],
    currentDoctor: null,
    isSignUp: false,
    globalDashboardData: null,
    globalDashboardDoctorId: null
};

export const i18n = {
    en: {
        memberDashboardTitle: 'Member Dashboard', trackPhoneLabel: 'Phone Number used for booking',
        appName: 'Relizane Medical', findDoctor: 'Find a Doctor', searchPlaceholder: '🔍 Search by name, specialty, or location...',
        allSpecialties: 'All Specialties', allMunicipalities: 'All Municipalities', loadingDoctors: 'Loading doctors...',
        noDoctorsFound: 'No doctors found matching your criteria.', registerDoctor: 'Register New Doctor',
        firstName: 'First Name *', firstNamePlaceholder: 'e.g. Amine', lastName: 'Last Name *', lastNamePlaceholder: 'e.g. Benali',
        phone: 'Phone Number *', phonePlaceholder: 'e.g. 0550 123 456', exactLocation: 'Exact Location / Address *',
        locationPlaceholder: 'Street, Building, Floor, Landmark...', specialty: 'Specialty *', specialtyPlaceholder: 'e.g. General Practice',
        municipality: 'Municipality (Baladiya) *', municipalityPlaceholder: 'e.g. Relizane', extraInfo: 'Extra Information',
        extraInfoPlaceholder: 'Working hours, consultation fees, languages spoken, diplomas...', registerBtn: 'Register Doctor',
        backToDirectory: '← Back to Directory', backToHome: '← Back to Directory', bookAppointment: 'Book Appointment',
        patientName: 'Patient Full Name *', patientNamePlaceholder: 'Full name', patientPhone: 'Patient Phone *',
        patientPhonePlaceholder: 'Contact number', appointmentDate: 'Appointment Date *', appointmentTime: 'Time *',
        confirmBooking: 'Confirm Booking', confirmDialogTitle: 'Confirm Appointment', confirmDialogMsg: 'Are you sure you want to book this appointment?',
        cancel: 'Cancel', doctorLogin: 'Doctor Login', loginDesc: 'Enter your Doctor ID and registered phone number to view your appointments.',
        patientLabel: 'Patient: ', statusPending: 'Pending', statusConfirmed: 'Confirmed', statusCancelled: 'Cancelled',
        bookNewAppointment: 'Book New Appointment', fetchingBookings: 'Fetching your bookings...', noUserBookings: 'No bookings registered to your account currently.',
        bookFirstAppt: 'Book your first appointment', fetchBookingsError: 'Connection error: Unable to fetch appointments.', bookingNumber: 'Booking ID: ',
        doctorId: 'Doctor ID', doctorIdPlaceholder: 'e.g. DOC-20240526-143022', loginPhone: 'Phone Number', loginPhonePlaceholder: 'Your registered phone',
        viewAppointments: 'View My Appointments', myAppointments: 'My Appointments', logout: 'Logout', thBookingId: 'Booking ID', thPatientName: 'Patient Name',
        thPhone: 'Phone', thDate: 'Date', thTime: 'Time', thStatus: 'Status', thActions: 'Actions', noAppointmentsMsg: 'No appointments found.',
        termsOfUse: 'Terms of Use',
        navHome: 'Directory', navTrack: 'Track Booking', navAdd: 'Add Doctor', navDashboard: 'Doctor Login', navLogin: 'Login',
        chatTitle: 'Medical Assistant',
        clinicProfileTitle: 'Clinic Profile & Services',
        clinicEmail: 'Clinic Email',
        clinicEmailPh: 'contact@clinic.com',
        whatsappNum: 'WhatsApp Number',
        whatsappPh: 'e.g. +213550000000',
        facebookLink: 'Facebook Link',
        facebookPh: 'https://facebook.com/...',
        mapLink: 'Clinic Location (Google Maps)',
        mapLinkPh: 'Google Maps link...',
        servicesProvided: 'Provided Services',
        servicesHelp: 'Add service categories (e.g., Pediatrics) then write sub-services separated by commas (,).',
        addServiceBtn: 'Add New Service Category',
        saveChangesBtn: 'Save Changes',
        forgotPassword: "Forgot Password?",
        mapLocation: 'Location Map',
        openInGoogleMaps: 'Open in Google Maps',
        ourServices: 'Our Services',
        catNamePh: 'Category Name (e.g. Dentistry)',
        svcItemsPh: 'Services (comma-separated, e.g. Whitening, Braces...)',
        whatsappBtn: 'WhatsApp',
        facebookBtn: 'Facebook',
        emailBtn: 'Email',
        changePasswordTitle: 'Change Password',
        changePassword: 'Change Password',
        heroBadge: 'The #1 Medical Platform',
        forgotPasswordTitle: 'Reset Password',
        trackBookingIdPlaceholder: 'e.g. APT-2024...',
        premiumServiceTitle: 'Clinic Management Service',
        certificatesLabel: 'Certificates & Exact Specialty',
        patientEmailOptional: 'Email (Optional for notifications)',
        memberProfileData: 'Profile & Basic Information',
        joinUsTitle: 'Are you a doctor? Boost your clinic\'s success with us!',
feature1Title: 'Smart Appointment Management',
feature1Desc: 'Say goodbye to chaos! Organize your schedule and receive bookings automatically.',
feature2Title: 'Strong Digital Presence',
feature2Desc: 'Showcase your expertise to thousands of patients searching for you in Relizane.',
feature3Title: 'Build Patient Trust',
feature3Desc: 'A transparent review system that increases your clinic\'s credibility.',
contactSalesBtn: 'Contact us to activate your account',
certificatesHelp: 'Write your certificates or specialties separated by commas (e.g., Pediatric Diploma, Algiers University Graduate).',
clinicImagesLabel: 'Clinic Images (to build patient trust)',
clinicImagesHelp: 'You can upload up to 3 images max (they will be saved and displayed on your profile).',
premiumServiceDesc: 'This premium service allows doctors to manage their appointments professionally. To get your clinic login credentials and subscribe, please contact the directory administration.',
contactAdminBtn: 'Request Doctor Account',
trackPhonePlaceholder: 'e.g. 0550 000 000',
certificatesPh: 'Write your certificates here...',
forgotPasswordDesc: 'Enter your registered email below and we will send you a link to set a new password.',
sendResetLink: 'Send Link',
changePasswordDesc: 'Please enter your new password (at least 6 characters).',
chatSubtitle: 'Available for instant reply',
chatWelcome: 'Hello! I am your AI assistant 🩺. How can I help you today? (e.g. "I need an eye doctor in Relizane" or "Find Dr. Amine")',
chatInputPlaceholder: 'Type your question here...',
chatToggleBtn: 'Chat with us',
chatLoadingDB: 'Sorry, the doctors database is currently loading. Please try again in a moment.',
chatNoResults: 'Sorry, I couldn\'t find any doctors matching your search. Try typing the name correctly, or mention the specialty and municipality.',
chatFoundPrefix: 'I found ',
chatFoundSuffix: ' doctors based on your request. Here are the top 3 results:',
chatExactResults: 'Here are the results matching your question:',
chatDoctorLabel: 'Doctor: ',
chatSpecLabel: 'Specialty: ',
chatPhoneLabel: 'Phone: ',
chatMunLabel: 'Municipality: ',
chatAddressLabel: 'Address: ',
chatBookDetailsBtn: 'View Details & Book',
        loginTitle: 'Member Login', signUpTitle: 'Create Account', loginBtn: 'Login', signUpBtn: 'Sign Up', googleSignIn: 'Sign in with Google', or: 'or',
        fullName: 'Full Name', fullNamePlaceholder: 'Your full name', email: 'Email *', emailPlaceholder: 'your@email.com', password: 'Password *',
        passwordPlaceholder: '••••••••', noAccount: "Don't have an account? Sign up", hasAccount: 'Already have an account? Login',
        loginRequired: 'Please login to add a doctor.', toastRegisterSuccess: 'Doctor registered! ID: ', toastRegisterError: 'Registration failed: ',
        toastBookingSuccess: 'Appointment confirmed! ID: ', toastBookingError: 'Booking failed: ', toastLoginError: 'Login failed: ',
        toastLoadError: 'Failed to load directory', loadingError: 'Unable to load doctors.', bookBtn: 'Book Appointment',
        toastAuthSuccess: 'Welcome! ', toastAuthError: 'Authentication failed: ', toastLogout: 'Logged out', weakPassword: 'Password must be at least 6 characters',
        invalidEmail: 'Invalid email address', userNotFound: 'No account found with this email', wrongPassword: 'Incorrect password', emailInUse: 'This email is already registered',
        footerRights: '© 2026 Relizane Medical Directory. All rights reserved.', privacyPolicy: 'Privacy Policy', contactUs: 'Contact Us',
        heroTitle: 'Relizane Medical Directory', registeredMember: 'Registered Member', myRecentBookings: 'My Recent Bookings',
        trackAnotherBooking: 'Track Another Booking', heroSubtitle: 'Your comprehensive platform to find doctors, clinics, and book medical appointments across all municipalities of Relizane.',
        enableBooking: 'Enable Bookings', disableBooking: 'Disable Bookings', bookingsClosed: 'Bookings Closed', toastToggleSuccess: 'Booking status updated', 
        toastToggleError: 'Failed to update status', trackBookingTitle: 'Track Booking Status', trackBookingDesc: 'Enter your booking ID to check if the doctor has confirmed it.',
        bookingIdLabel: 'Booking ID (APT)', trackSearchBtn: 'Search Booking', workingHoursTitle: 'Working Days & Hours Settings',
        workingHoursDesc: 'Enable your working days and set the start/end time for each day.', saveHoursBtnText: 'Save Hours',
        scheduleTitle: 'Available Schedule', fallbackTitle: 'Available Working Hours', dailyTxt: 'Daily:', selectDateFirst: 'Please select an appointment date first to see available times...',
        invalidDate: 'Please enter a valid date...', selectSpec: '-- Select Specialty --', ratingLabel: 'What is your rating?',
        reviewPlaceholder: 'Write your experience to help others...', submitReviewBtn: 'Publish Review', loginToReviewText: 'You must log in to add a review.',
        selectMun: '-- Select Municipality --', doctorOff: 'Doctor is not available on this day, please choose another date.', noSlots: 'Sorry, no available time slots on this day.',
        morningSession: 'Morning Session', eveningSession: 'Afternoon / Evening', sun: 'Sunday', mon: 'Monday', tue: 'Tuesday', wed: 'Wednesday', thu: 'Thursday', fri: 'Friday', sat: 'Saturday',
        'الأرطوفونيا (تقويم النطق) - Speech Therapy': 'Speech Therapy', 'الأشعة - Radiology': 'Radiology', 'الأمراض الجلدية - Dermatology': 'Dermatology', 'الأمراض الصدرية - Pulmonology': 'Pulmonology',
        'الأمراض المعدية - Infectious Disease': 'Infectious Disease', 'الأنف والأذن والحنجرة - ENT (Otolaryngology)': 'ENT (Otolaryngology)', 'التخدير - Anesthesiology': 'Anesthesiology',
        'التغذية العلاجية - Clinical Nutrition': 'Clinical Nutrition', 'الجراحة التجميلية - Plastic Surgery': 'Plastic Surgery', 'الجراحة العامة - General Surgery': 'General Surgery',
        'الطب الباطني - Internal Medicine': 'Internal Medicine', 'الطب المخبري (التحاليل) - Laboratory Medicine': 'Laboratory Medicine', 'الطب النفسي - Psychiatry': 'Psychiatry',
        'العلاج الطبيعي وإعادة التأهيل - Physiotherapy & Rehabilitation': 'Physiotherapy & Rehabilitation', 'الغدد الصماء والسكري - Endocrinology': 'Endocrinology', 'أمراض الجهاز الهضمي - Gastroenterology': 'Gastroenterology',
        'أمراض الدم - Hematology': 'Hematology', 'أمراض الروماتيزم والمفاصل - Rheumatology': 'Rheumatology', 'أمراض القلب - Cardiology': 'Cardiology', 'أمراض الكلى - Nephrology': 'Nephrology',
        'أمراض النساء والتوليد - Gynecology & Obstetrics': 'Gynecology & Obstetrics', 'جراحة الأوعية الدموية - Vascular Surgery': 'Vascular Surgery', 'جراحة العظام - Orthopedics': 'Orthopedics',
        'جراحة القلب والصدر - Cardiothoracic Surgery': 'Cardiothoracic Surgery', 'جراحة المخ والأعصاب - Neurosurgery': 'Neurosurgery', 'جراحة المسالك البولية - Urology': 'Urology',
        'طب الأعصاب - Neurology': 'Neurology', 'طب الأسرة - Family Medicine': 'Family Medicine', 'طب الأسنان - Dentistry': 'Dentistry', 'طب الأطفال - Pediatrics': 'Pediatrics',
        'طب الأورام - Oncology': 'Oncology', 'طب الحساسية والمناعة - Allergy & Immunology': 'Allergy & Immunology', 'طب الشيخوخة - Geriatrics': 'Geriatrics', 'طب الطوارئ - Emergency Medicine': 'Emergency Medicine',
        'طب العيون - Ophthalmology': 'Ophthalmology', 'طب عام - General Medicine': 'General Medicine', 'علم الوراثة الطبية - Medical Genetics': 'Medical Genetics',
        'أولاد سيدي الميهوب': 'Ouled Sidi Mihoub', 'أولاد يعيش': 'Ouled Yaich', 'الحاسي': 'El Hassi', 'الحمادنة': 'El Hamadna', 'القطار': 'El Guettar', 'القلعة': 'El Kalaa',
        'المطمر': 'El Matmar', 'المرجة': 'El Merdja', 'الولجة': 'El Oueldja', 'بن داود': 'Bendaoud', 'بني درقون': 'Beni Dergoun', 'بني زنطيس': 'Beni Zentis',
        'بلعسل بوزقزة': 'Belassel Bouzegza', 'جديوية': 'Djidiouia', 'حد الشكالة': 'Had Echkalla', 'حمري': 'Hamri', 'دار بن عبد الله': 'Dar Benabdellah', 'رمكة': 'Ramka',
        'زمورة': 'Zemmoura', 'سوق الحد': 'Souk El Had', 'سيدي امحمد بن علي': 'Sidi Mhamed Ben Ali', 'سيدي امحمد بن عودة': 'Sidi Mhamed Benaouda', 'سيدي خطاب': 'Sidi Khettab',
        'سيدي سعادة': 'Sidi Saada', 'سيدي لزرق': 'Sidi Lazreg', 'عين الرحمة': 'Ain Rahma', 'عين طارق': 'Ain Tarek', 'عمي موسى': 'Ammi Moussa', 'غليزان': 'Relizane',
        'لحلاف': 'Lahlef', 'مازونة': 'Mazouna', 'مديونة': 'Mediouna', 'منداس': 'Mendes', 'وادي الجمعة': 'Oued El Djemaa', 'وادي السلام': 'Oued Essalem', 'وادي رهيو': 'Oued Rhiou',
        'واريزان': 'Ouarizane', 'يلل': 'Yellel'
      },
      ar: {
        memberDashboardTitle: 'لوحة تحكم العضو', trackPhoneLabel: 'رقم الهاتف المرفق بالحجز', appName: 'دليل أطباء غليزان', findDoctor: 'ابحث عن طبيب',
        searchPlaceholder: '🔍 ابحث بالاسم أو الاختصاص أو الموقع...', allSpecialties: 'جميع الاختصاصات', allMunicipalities: 'جميع البلديات', loadingDoctors: 'جاري تحميل قائمة الأطباء...',
        noDoctorsFound: 'لا يوجد أطباء مطابقون لبحثك.', registerDoctor: 'تسجيل طبيب جديد', firstName: 'الاسم *', firstNamePlaceholder: 'مثال: أمين',
        lastName: 'اللقب *', lastNamePlaceholder: 'مثال: بن علي', phone: 'رقم الهاتف *', phonePlaceholder: 'مثال: 0550 123 456', exactLocation: 'العنوان الدقيق *',
        locationPlaceholder: 'الشارع، المبنى، الطابق، معلم قريب...', specialty: 'الاختصاص *', specialtyPlaceholder: 'مثال: الطب العام', municipality: 'البلدية *',
        chatTitle: 'المستشار الطبي',
        chatSubtitle: 'متاح للرد الفوري',
        chatWelcome: 'أهلاً بك في دليل أطباء غليزان. أنا مساعدك الآلي🩺. كيف يمكنني مساعدتك اليوم؟ (مثال: "أريد رقم طبيب عيون في غليزان" أو "ابحث عن الدكتور أمين")',
        chatInputPlaceholder: 'اكتب سؤالك هنا...',
        chatToggleBtn: 'تحدث معنا',
        chatLoadingDB: 'عذراً، جاري تحميل قاعدة بيانات الأطباء حالياً. يرجى المحاولة بعد لحظات.',
        chatNoResults: 'عذراً، لم أتمكن من العثور على أطباء يطابقون بحثك. حاول كتابة اسم الطبيب بدقة، أو ذكر الاختصاص والبلدية.',
        chatFoundPrefix: 'وجدت ',
        chatFoundSuffix: ' أطباء بناءً على طلبك. إليك أبرز 3 نتائج:',
        chatExactResults: 'تفضل، لقد وجدت هذه النتائج المطابقة لسؤالك:',
        chatDoctorLabel: 'الدكتور(ة): ',
        chatSpecLabel: 'الاختصاص: ',
        termsOfUse: 'شروط الاستعمال',
        chatPhoneLabel: 'الهاتف: ',
        chatMunLabel: 'البلدية: ',
        chatAddressLabel: 'العنوان: ',
        chatBookDetailsBtn: 'عرض التفاصيل والحجز',
        forgotPasswordTitle: 'استعادة كلمة المرور',
        forgotPasswordDesc: 'أدخل بريدك الإلكتروني المسجل أدناه وسنرسل لك رابطاً لتعيين كلمة مرور جديدة.',
        sendResetLink: 'إرسال الرابط',
        clinicProfileTitle: 'ملف العيادة والخدمات',
        clinicEmail: 'البريد الإلكتروني للعيادة',
        clinicEmailPh: 'contact@clinic.com',
        whatsappNum: 'رقم الواتساب',
        whatsappPh: 'مثال: 213550000000+',
        facebookLink: 'رابط حساب الفيسبوك',
        facebookPh: 'https://facebook.com/...',
        mapLink: 'رابط موقع العيادة (Google Maps)',
        mapLinkPh: 'رابط خرائط جوجل...',
        servicesProvided: 'الخدمات المقدمة (جدول الخدمات)',
        servicesHelp: 'أضف فئات الخدمات (مثال: طب الأطفال) ثم اكتب الخدمات التابعة لها مفصولة بفاصلة (,)',
        addServiceBtn: 'إضافة فئة خدمات جديدة',
        saveChangesBtn: 'حفظ التغييرات',
        mapLocation: 'الموقع الجغرافي',
        openInGoogleMaps: 'فتح في خرائط جوجل',
        ourServices: 'خدماتنا',
        catNamePh: 'اسم الفئة (مثال: طب الأسنان)',
        svcItemsPh: 'الخدمات (افصل بينها بفاصلة، مثال: تبييض، تقويم...)',
        whatsappBtn: 'واتساب',
        facebookBtn: 'فيسبوك',
        emailBtn: 'إيميل',
        forgotPassword: "هل نسيت كلمة المرور؟",
        changePasswordTitle: 'تغيير كلمة المرور',
        changePassword: 'تغيير كلمة المرور',
        heroBadge: 'المنصة الطبية الأولى',
        trackBookingIdPlaceholder: 'مثال: APT-2024...',
        trackPhonePlaceholder: 'مثال:  0550000000',
        certificatesPh: 'اكتب شهاداتك وتخصصاتك هنا...',
        premiumServiceTitle: 'خدمة إدارة العيادات',
        certificatesLabel: 'الشهادات والتخصص الدقيق',
        patientEmailOptional: 'البريد الإلكتروني (اختياري للإشعارات)',
        memberProfileData: 'الملف الشخصي والبيانات الأساسية',
        certificatesHelp: 'اكتب شهاداتك أو تخصصاتك مفصولة بفاصلة (مثال: دبلوم طب أطفال، خريج جامعة الجزائر).',
        clinicImagesLabel: 'صور العيادة (لإعطاء ثقة للمرضى)',
        clinicImagesHelp: 'يمكنك رفع حتى 3 صور كحد أقصى (سيتم حفظها وعرضها في ملفك).',
        premiumServiceDesc: 'هذه الخدمة المتقدمة تتيح للأطباء إدارة حجوزاتهم باحترافية تامة. للحصول على بيانات الدخول الخاصة بعيادتك والاشتراك في الخدمة، يرجى التواصل مع إدارة الدليل.',
        contactAdminBtn: 'طلب حساب طبيب',
       changePasswordDesc: 'يرجى إدخال كلمة المرور الجديدة (يجب أن تتكون من 6 أحرف على الأقل).',
        joinUsTitle: 'هل أنت طبيب؟ ضاعف نجاح عيادتك معنا!',
        feature1Title: 'إدارة ذكية للمواعيد',
        feature1Desc: 'وداعاً للفوضى! نظم جدول عيادتك واستقبل الحجوزات بنظام آلي سهل.',
        feature2Title: 'حضور رقمي قوي',
        feature2Desc: 'اعرض خبراتك لآلاف المرضى الباحثين عنك في غليزان.',
        feature3Title: 'بناء ثقة المرضى',
        feature3Desc: 'نظام تقييمات شفاف يزيد من مصداقية عيادتك.',
        contactSalesBtn: 'تواصل معنا لتفعيل حسابك',
        municipalityPlaceholder: 'مثال: غليزان', extraInfo: 'معلومات إضافية', extraInfoPlaceholder: 'أوقات العمل، أجرة الكشف، اللغات المحكية، الشهادات...', registerBtn: 'تسجيل الطبيب',
        backToDirectory: '→ العودة للدليل', backToHome: '→ العودة للدليل', bookAppointment: 'حجز موعد', patientName: 'اسم المريض الكامل *', patientNamePlaceholder: 'الاسم الكامل',
        patientPhone: 'هاتف المريض *', patientPhonePlaceholder: 'رقم الاتصال', appointmentDate: 'تاريخ الموعد *', appointmentTime: 'الوقت *', confirmBooking: 'تأكيد الحجز',
        confirmDialogTitle: 'تأكيد الموعد', confirmDialogMsg: 'هل أنت متأكد من حجز هذا الموعد؟', cancel: 'إلغاء', doctorLogin: 'تسجيل دخول الطبيب', patientLabel: 'المريض: ',
        statusPending: 'قيد الانتظار', statusConfirmed: 'مؤكد', statusCancelled: 'ملغى', bookNewAppointment: 'حجز موعد جديد', fetchingBookings: 'جاري جلب حجوزاتك...',
        noUserBookings: 'لا توجد حجوزات مسجلة بحسابك حالياً.', bookFirstAppt: 'احجز موعدك الأول', selectSpec: '-- اختر الاختصاص --', selectMun: '-- اختر البلدية --',
fetchBookingsError: 'خطأ في الاتصال: تعذر جلب المواعيد.', bookingNumber: 'رقم الحجز: ', loginDesc: 'أدخل كلمة المرور  ورقم الهاتف المسجل لعرض مواعيدك.', doctorId: 'معرف الطبيب',
        doctorIdPlaceholder: 'مثال: DOC-20240526-143022', loginPhone: 'رقم الهاتف', loginPhonePlaceholder: 'الهاتف المسجل', viewAppointments: 'عرض مواعيدي', myAppointments: 'مواعيدي',
        logout: 'تسجيل الخروج', thBookingId: 'رقم الحجز', thPatientName: 'اسم المريض', thPhone: 'الهاتف', thDate: 'التاريخ', thTime: 'الوقت', thStatus: 'الحالة', thActions: 'الإجراءات',
        noAppointmentsMsg: 'لا توجد مواعيد.', registeredMember: 'عضو مسجل', myRecentBookings: 'حجوزاتي الأخيرة', trackAnotherBooking: 'تتبع حجز آخر', ratingLabel: 'ما هو تقييمك؟',
        reviewPlaceholder: 'اكتب تجربتك مع هذا الطبيب لمساعدة الآخرين...', submitReviewBtn: 'نشر التقييم', loginToReviewText: 'يجب تسجيل الدخول لإضافة تقييم.', navHome: 'الدليل',
        navTrack: 'تتبع حجزي', navAdd: 'إضافة طبيب', navDashboard: 'دخول الأطباء', navLogin: 'تسجيل الدخول', loginTitle: 'تسجيل دخول الأعضاء', signUpTitle: 'إنشاء حساب جديد',
        loginBtn: 'دخول', signUpBtn: 'سجل الآن', googleSignIn: 'تسجيل الدخول عبر غوغل', or: 'أو', fullName: 'الاسم الكامل', fullNamePlaceholder: 'اسمك الكامل', email: 'البريد الإلكتروني *',
        emailPlaceholder: 'your@email.com', password: 'كلمة المرور *', passwordPlaceholder: '••••••••', noAccount: 'ليس لديك حساب؟ سجل الآن', hasAccount: 'لديك حساب بالفعل؟ سجل الدخول',
        loginRequired: 'يجب تسجيل الدخول لإضافة طبيب.', toastRegisterSuccess: 'تم تسجيل الطبيب! المعرف: ', toastRegisterError: 'فشل التسجيل: ', toastBookingSuccess: 'تم تأكيد الموعد! رقم الحجز: ',
        toastBookingError: 'فشل الحجز: ', toastLoginError: 'فشل تسجيل الدخول: ', toastLoadError: 'فشل تحميل الدليل', loadingError: 'تعذر تحميل قائمة الأطباء.', bookBtn: 'حجز موعد',
        toastAuthSuccess: 'أهلاً! ', toastAuthError: 'فشل المصادقة: ', toastLogout: 'تم تسجيل الخروج', weakPassword: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل', invalidEmail: 'بريد إلكتروني غير صالح',
        userNotFound: 'لا يوجد حساب بهذا البريد', wrongPassword: 'كلمة المرور غير صحيحة', emailInUse: 'هذا البريد مسجل بالفعل', footerRights: '© 2026 دليل أطباء غليزان. جميع الحقوق محفوظة.',
        privacyPolicy: 'سياسة الخصوصية', contactUs: 'اتصل بنا', heroTitle: 'دليل أطباء ولاية غليزان', heroSubtitle: 'منصتك الشاملة للبحث عن الأطباء وحجز المواعيد الطبية في ولاية غليزان.',
        enableBooking: 'تفعيل الحجوزات', disableBooking: 'إيقاف الحجوزات', bookingsClosed: 'الحجوزات مغلقة حالياً', toastToggleSuccess: 'تم تحديث حالة الحجز', toastToggleError: 'فشل تحديث الحالة',
        trackBookingTitle: 'تتبع حالة الحجز', trackBookingDesc: 'أدخل رقم الحجز الذي حصلت عليه للتحقق من تأكيد الطبيب.', bookingIdLabel: 'رقم الحجز (APT)', trackSearchBtn: 'بحث عن الحجز',
        workingHoursTitle: 'إعدادات أيام وأوقات العمل', workingHoursDesc: 'قم بتفعيل الأيام التي تعمل فيها وحدد وقت البداية والنهاية لكل يوم.', saveHoursBtnText: 'حفظ الأوقات',
        scheduleTitle: 'جدول العمل المتاح للطبيب', fallbackTitle: 'أوقات العمل المتاحة', dailyTxt: 'يومياً:', selectDateFirst: 'يرجى تحديد تاريخ الموعد أولاً لعرض الأوقات المتاحة...',
        invalidDate: 'يرجى إدخال تاريخ صحيح...', doctorOff: 'الطبيب لا يعمل في هذا اليوم، يرجى اختيار تاريخ آخر.', noSlots: 'عذراً، لا توجد فترات زمنية كافية للحجز في هذا اليوم.',
        morningSession: 'الفترة الصباحية', eveningSession: 'الفترة المسائية', sun: 'الأحد', mon: 'الإثنين', tue: 'الثلاثاء', wed: 'الأربعاء', thu: 'الخميس', fri: 'الجمعة', sat: 'السبت',
        'الأرطوفونيا (تقويم النطق) - Speech Therapy': 'الأرطوفونيا (تقويم النطق)', 'الأشعة - Radiology': 'الأشعة', 'الأمراض الجلدية - Dermatology': 'الأمراض الجلدية', 'الأمراض الصدرية - Pulmonology': 'الأمراض الصدرية',
        'الأمراض المعدية - Infectious Disease': 'الأمراض المعدية', 'الأنف والأذن والحنجرة - ENT (Otolaryngology)': 'الأنف والأذن والحنجرة', 'التخدير - Anesthesiology': 'التخدير', 'التغذية العلاجية - Clinical Nutrition': 'التغذية العلاجية',
        'الجراحة التجميلية - Plastic Surgery': 'الجراحة التجميلية', 'الجراحة العامة - General Surgery': 'الجراحة العامة', 'الطب الباطني - Internal Medicine': 'الطب الباطني', 'الطب المخبري (التحاليل) - Laboratory Medicine': 'الطب المخبري (التحاليل)',
        'الطب النفسي - Psychiatry': 'الطب النفسي', 'العلاج الطبيعي وإعادة التأهيل - Physiotherapy & Rehabilitation': 'العلاج الطبيعي وإعادة التأهيل', 'الغدد الصماء والسكري - Endocrinology': 'الغدد الصماء والسكري',
        'أمراض الجهاز الهضمي - Gastroenterology': 'أمراض الجهاز الهضمي', 'أمراض الدم - Hematology': 'أمراض الدم', 'أمراض الروماتيزم والمفاصل - Rheumatology': 'أمراض الروماتيزم والمفاصل', 'أمراض القلب - Cardiology': 'أمراض القلب',
        'أمراض الكلى - Nephrology': 'أمراض الكلى', 'أمراض النساء والتوليد - Gynecology & Obstetrics': 'أمراض النساء والتوليد', 'جراحة الأوعية الدموية - Vascular Surgery': 'جراحة الأوعية الدموية', 'جراحة العظام - Orthopedics': 'جراحة العظام',
        'جراحة القلب والصدر - Cardiothoracic Surgery': 'جراحة القلب والصدر', 'جراحة المخ والأعصاب - Neurosurgery': 'جراحة المخ والأعصاب', 'جراحة المسالك البولية - Urology': 'جراحة المسالك البولية', 'طب الأعصاب - Neurology': 'طب الأعصاب',
        'طب الأسرة - Family Medicine': 'طب الأسرة', 'طب الأسنان - Dentistry': 'طب الأسنان', 'طب الأطفال - Pediatrics': 'طب الأطفال', 'طب الأورام - Oncology': 'طب الأورام', 'طب الحساسية والمناعة - Allergy & Immunology': 'طب الحساسية والمناعة',
        'طب الشيخوخة - Geriatrics': 'طب الشيخوخة', 'طب الطوارئ - Emergency Medicine': 'طب الطوارئ', 'طب العيون - Ophthalmology': 'طب العيون', 'طب عام - General Medicine': 'طب عام', 'علم الوراثة الطبية - Medical Genetics': 'علم الوراثة الطبية',
        'أولاد سيدي الميهوب': 'أولاد سيدي الميهوب', 'أولاد يعيش': 'أولاد يعيش', 'الحاسي': 'الحاسي', 'الحمادنة': 'الحمادنة', 'القطار': 'القطار', 'القلعة': 'القلعة', 'المطمر': 'المطمر', 'المرجة': 'المرجة', 'الولجة': 'الولجة', 'بن داود': 'بن داود',
        'بني درقون': 'بني درقون', 'بني زنطيس': 'بني زنطيس', 'بلعسل بوزقزة': 'بلعسل بوزقزة', 'جديوية': 'جديوية', 'حد الشكالة': 'حد الشكالة', 'حمري': 'حمري', 'دار بن عبد الله': 'دار بن عبد الله', 'رمكة': 'رمكة', 'زمورة': 'زمورة',
        'سوق الحد': 'سوق الحد', 'سيدي امحمد بن علي': 'سيدي امحمد بن علي', 'سيدي امحمد بن عودة': 'سيدي امحمد بن عودة', 'سيدي خطاب': 'سيدي خطاب', 'سيدي سعادة': 'سيدي سعادة', 'سيدي لزرق': 'سيدي لزرق', 'عين الرحمة': 'عين الرحمة',
        'عين طارق': 'عين طارق', 'عمي موسى': 'عمي موسى', 'غليزان': 'غليزان', 'لحلاف': 'لحلاف', 'مازونة': 'مازونة', 'مديونة': 'مديونة', 'منداس': 'منداس', 'وادي الجمعة': 'وادي الجمعة', 'وادي السلام': 'وادي السلام',
        'وادي رهيو': 'وادي رهيو', 'واريزان': 'واريزان', 'يلل': 'يلل'
      }
    };
